apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: ranfa23/auth
      context: auth
      sync:
        manual:
          - src: src/***/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ranfa23/orders
      context: orders
      sync:
        manual:
          - src: src/***/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ranfa23/tickets
      context: tickets
      sync:
        manual:
          - src: src/***/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ranfa23/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - infra/k8s/*
deploy:
  kubectl: {}
